### ISSUE TITLE
Link to list of all playable songs

### ISSUE THREAD

**Issue by za419** [kenellorando/cadence#100]
@KarenwithaKay wants there to be a link to an index of all songs which are available in Cadence, so one can know. I experimented with fetching this myself, by searching for the most common 10,000 words, but it tended to, uh, crash.

@kenellorando, could we write a page in Node that just queries the database for all records and returns a list of all songs?

**Comment by kenellorando** [comment]
Now in progress. The database populator will be integrated into 4.0 server as a function, and will generate a text file listing all music data each time it is run. The populator function will only be run on init and when a change in the music directory is observed. Therefore, this library text file will only be updated on startup or when a change is made in the filesystem.

I am not for the idea of running a new database query each time a user asks for the library list, because it's essentially the same as running a `SELECT *`, which can be spammed and add unnecessary stress to the server.

**Comment by za419** [comment]
Agreed. DBP can dump a JSON file containing a copy of the library, and we just serve the current copy on API call to library

**Comment by kenellorando** [comment]
Full library listing data available on `/api/aria1/library`
