### ISSUE TITLE
Getting a constant panic on cadence, web interface bouncing

### ISSUE THREAD

**Issue by hiro24** [kenellorando/cadence#240]
The following loops over and over again after starting. If I go to the actual icecast site I can hear and stream music. But if I go to the cadence site nothing. Sometimes if I refresh I can see the UI but it's pretty much empty. It seems to be bouncing trying to start. In the console this error is looping constantly.

```
postgres    | 2023-03-08 19:20:08.809 UTC [37] ERROR:  extension "fuzzystrmatch" already exists
postgres    | 2023-03-08 19:20:08.809 UTC [37] STATEMENT:  CREATE EXTENSION fuzzystrmatch
cadence     | 2023/03/08 19:20:08 [INFO ][POSTGRESINIT] fuzzystrmatch already enabled on metadata database.
postgres    | 2023-03-08 19:20:08.810 UTC [22] LOG:  checkpoint starting: immediate force wait
postgres    | 2023-03-08 19:20:08.820 UTC [22] LOG:  checkpoint complete: wrote 44 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.002 s, total=0.011 s; sync files=34, longest=0.001 s, average=0.001 s; distance=4439 kB, estimate=4452 kB
cadence     | 2023/03/08 19:20:08 [INFO ][DBPOPULATE] Database population completed.
cadence     | 2023/03/08 19:20:08 [INFO ][MAIN] Starting Cadence on port <:8080>.
cadence     | panic: interface conversion: interface {} is nil, not string
cadence     | 
cadence     | goroutine 23 [running]:
cadence     | main.icecastMonitor.func2()
cadence     |   /cadence/api_actions.go:213 +0xc29
cadence     | main.icecastMonitor.func3()
cadence     |   /cadence/api_actions.go:245 +0x31
cadence     | created by main.icecastMonitor
cadence     |   /cadence/api_actions.go:242 +0xaf
cadence exited with code 2

```

**Comment by kenellorando** [comment]
Hi @hiro24 and welcome! Thanks for your report. I have some ideas why this may be happening.

Sometimes Cadence starts up before Icecast itself has anything playing, and this was fine. Cadence historically handled this by setting now-playing as dashes ("-") if it sees nothing playing, but a recent reorganization in code appears to have bugged this behavior out. This, independently, seems easy enough to fix.

What makes this trickier is that you mentioned that you can hear audio when you directly connect to Icecast. What this suggests is that Icecast is actually working fine, but Cadence is either having trouble connecting to Icecast or reading whatever it is saying it is playing.

I have a few requests to help isolate the issue further:

1. Can you post your configs (`cadence.env` and `icecast.xml`)? Please redact any custom passwords you may have set.
2. Can you also, in `cadence.env`, set `CSERVER_LOGLEVEL` to `5`, and try to share the output again? This might help show exactly what is failing.
3. Out of curiosity, does the audio file you are trying to play possibly lack title or artist metadata? Does it have any different or special characters?

**Comment by hiro24** [comment]
So I turned up logging and based on your 3rd suggestion I checked my mp3 files. It turns out none of them had any metadata in them. Out of an abundance of caution I populated the metadata of my files and I'm now able to hear the stream on the cadence web interface.

However, it's still not completely working correctly. I'm seeing behavior that you described where it "looks" like nothing is playing. Only dashes and no album art. Even though it is able to play audio. Also, the request search appears not to be working. Here's a snippet from the console.

`cadence     | 2023/03/09 15:25:45 [DEBUG][SEARCHBYTITLEARTIST] Searching database for: 'We Built This City by Starship
cadence     | 2023/03/09 15:25:45 http: panic serving 172.22.0.1:35586: runtime error: index out of range [0] with length 0
cadence     | goroutine 2283 [running]:
cadence     | net/http.(*conn).serve.func1()
cadence     |   /usr/local/go/src/net/http/server.go:1854 +0xbf
cadence     | panic({0x786c60, 0xc0000c0558})
cadence     |   /usr/local/go/src/runtime/panic.go:890 +0x263
cadence     | main.NowPlayingMetadata.func1({0x847fa0, 0xc00016c1c0}, 0xffffffffffffffff?)
cadence     |   /cadence/api.go:127 +0x179
cadence     | net/http.HandlerFunc.ServeHTTP(0xc00051ae80?, {0x847fa0?, 0xc00016c1c0?}, 0x40d0e8?)
cadence     |   /usr/local/go/src/net/http/server.go:2122 +0x2f
cadence     | net/http.(*ServeMux).ServeHTTP(0x0?, {0x847fa0, 0xc00016c1c0}, 0xc000118900)
cadence     |   /usr/local/go/src/net/http/server.go:2500 +0x149
cadence     | net/http.serverHandler.ServeHTTP({0xc000333170?}, {0x847fa0, 0xc00016c1c0}, 0xc000118900)
cadence     |   /usr/local/go/src/net/http/server.go:2936 +0x316
cadence     | net/http.(*conn).serve(0xc00013e990, {0x848228, 0xc00006e420})
cadence     |   /usr/local/go/src/net/http/server.go:1995 +0x612
cadence     | created by net/http.(*Server).Serve
cadence     |   /usr/local/go/src/net/http/server.go:3089 +0x5ed
cadence     | 2023/03/09 15:25:45 [DEBUG][SEARCHBYTITLEARTIST] Searching database for: 'We Built This City by Starship
cadence     | 2023/03/09 15:25:45 [DEBUG][SEARCH] Search request from client 172.22.0.1:35610.
cadence     | 2023/03/09 15:25:45 [DEBUG][SEARCHBYQUERY] Searching database for query: ''
cadence     | 2023/03/09 15:25:45 [INFO ][ICECASTMONITOR] Listener count: <0>
cadence     | 2023/03/09 15:25:46 [INFO ][ICECASTMONITOR] Listener count: <1>
cadence     | 2023/03/09 15:25:51 [INFO ][ICECASTMONITOR] Listener count: <2>
cadence     | 2023/03/09 15:25:52 [INFO ][ICECASTMONITOR] Listener count: <1>
postgres    | 2023-03-09 15:26:03.206 UTC [22] LOG:  checkpoint complete: wrote 984 buffers (6.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=98.462 s, sync=0.012 s, total=98.482 s; sync files=279, longest=0.002 s, average=0.001 s; distance=4459 kB, estimate=4459 kB
`
This happens if I refresh the page or when I go to it. I tried stopping the cadence container and restarting it, thinking if everything else was running well after cadence started maybe that would correct the behavior. But it didn't.

**Comment by kenellorando** [comment]
@hiro24 I had a conversation with @za419, maintainer of CadenceBot, a Discord client for Cadence, and our top suspicion right now is that your `CSERVER_MUSICDIR` set in `cadence.env` may not exactly match the same path configured in `liquidsoap.liq`. 

Our logic for suspecting this is because we know the following is true:

- ✅ The audio stream alone through Icecast works, so the audio file is valid. 
- ✅ Icecast, as you mentioned, displays title and artist properly, so the file also has valid metadata.
- ✅ Cadence is able to connect to Icecast, because the provided log shows `Searching database for: 'We Built This City by Starship`, whose title and artist are pulled directly from Icecast. Icecast is aware of some select file metadata like title and artist, but not all of it. Under the hood, Cadence uses the title and artist playing from the Icecast stream in a search against its own database to get the rest of its data, like the path to its album artwork.
- ✅ At least from what is provided, we do not see any relevant database query error messages, implying that the search against the database is working. `runtime error: index out of range [0] with length 0` suggests that the database search is simply returning no results for Cadence to work with.

Since no results are returned, we believe that Cadence's own database was not populated with anything. So, for our next steps, can you try:

1. Verify that in `cadence.env`, `CSERVER_MUSICDIR` exactly matches the path to music that is set in `liquidsoap.liq`.
3. If you verify that they are the same, we're also requesting you provide your `cadence.env` and `liquidsoap.liq` files (passwords redacted) here, so we can check for anything else that might be causing this issue, and we can try to replicate.

**Comment by hiro24** [comment]
OK I GOT IT!

So the path in cadence.env matched liquidsoap.liq. 

What DIDN'T match was in my docker-compose.yml. I'd configured the volume that points to /music to where my music was stored in the liquidsoap section. But I missed that it was also set in the cadence section. There it was still set to /music:/music. Once I pointed that to the right place, everything took off.

1000% my fault on that part. Sorry about the confusion and thanks for helping me troubleshoot it.

**Comment by za419** [comment]
Wow, I didn't think at all about (potentially) needing to change the volume mount in both places in docker-compose.yml...

Good catch, @hiro24 - Perhaps we can take the opportunity on our side to make an improvement and document this somewhere, since I can definitely imagine someone else running into this again. Perhaps we could start a "Troubleshooting" section somewhere and start with this?

Personally, and I'm sure @kenellorando would agree, I think it's good for us to see pain points others have with setting this up or running it, since we're a little more used to all of it - So thanks for giving us the chance to learn from you!

**Comment by hiro24** [comment]
Absolutely! If it can be broke I'm your guy. :) But other than that everything went pretty smooth. I would say I'm not sure that setting ```CSERVER_MUSIC_DIR``` to an absolute path would work, since it's docker'ized. (I could be wrong) But that's why I just set /music to my dir in the docker-compose.yml. 

Keep up the great work.

**Comment by kenellorando** [comment]
I'll update our installation documentation. This highlights some good potential changes. That was a great catch! We appreciate your report and working through this too, @hiro24!
